postgreSQL-app-name: wpp-message

quarkus:
  banner:
    path: banner.txt
  # datasource configuration
  datasource:
    db-kind: postgresql
    username: ${DB_JDBC_USER:postgres}
    password: ${DB_JDBC_PASSWORD:postgres}
    jdbc:
      url: ${DB_JDBC_URL:jdbc:postgresql://localhost:5432/wpp_message?ApplicationName=${postgreSQL-app-name}}
  hibernate-orm:
    database:
      generation: validate
  http:
    cors:
      ~: true
      origins: /.*/
    port: ${PORT:8620}
    test-port: 8084
    root-path: /api
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    locations: db/migration
    placeholders:
      public_schema: public
  hibernate-validator:
    method-validation: none